run:
  issues-exit-code: 3

linters-settings:
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 140
  goconst:
    min-len: 3
    min-occurrences: 3
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: var-naming
        enabled: true
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - importShadow
      - commentedOutCode
      - unnamedResult
      - paramTypeCombine

linters:
  disable:
    - goimports # not necessary
    - unused # usually unused code left by design
  enable:
    - goconst # Finds repeated strings that could be replaced by a constant
    - gosec # Inspects source code for security problems
    - revive # Drop-in replacement of golint
    - gocritic # Check for bugs, performance and style issues
    - funlen # Detection of long functions
    - errcheck # Checking for unchecked errors in go programs
    - exportloopref # Checks for pointers to enclosing loop variables
    - whitespace # Detection of leading and trailing whitespace
    - lll # Reports long lines
    - gocognit # Cognitive complexity of functions - complex functions should be split into smaller ones
    - misspell # Finds commonly misspelled English words in comments
    - maintidx # Maintainability index of each function - complex functions should be split into smaller ones

issues:
  exclude-rules:
    # Exclude some linters
    - path: (.+)_test.go
      linters:
        - funlen
        - lll
        - dupl
        - maintidx
        - gocognit
